server:
  port: 8888
spring:
  application:
    name: microservices-bank-config
  cloud:
    config:
      server:
        git:
          ignore-local-ssh-settings: true
          default-label: main
          uri: https://github.com/csanmont/microservices-bank-config.git
          search-paths: config-data
          username: csanmont
          password: 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
