server:
  port: 8090
  
spring:
  application:
    name: microservice-bank-gateway
  cloud:
    gateway:
      routes:
        - id: microservice-credit-accounts
          uri: http://localhost:8083
          predicates: 
          - Path=/api/credit/accounts/**
          
      discovery:
        locator:
          enabled: true
    loadbalancer:
      ribbon:
        enabled: false
        
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
  service-url: 
    default-zone: http://${eureka.instance.hostname}:${server.port}/eureka    