server:
  port: 8082
spring:
  application:
    name: microservice-passive-accounts
  data:
    mongodb:
      database: BankPassiveAccounts
      host: localhost
      port: 27017
      uri: mongodb://localhost:27017/BankPassiveAccounts
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration