server:
  port: 8082
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    service-url: 
      default-zone: http://bank-discovery:8761/eureka  
  
spring:
  application:
    name: microservice-passive-accounts
  data:
    mongodb:
      #database: BankPassiveAccounts
      #host: localhost
      #port: 27017
      uri: mongodb+srv://csanmont:csanmont@cluster0.bxnzqcx.mongodb.net/BankPassiveAccounts?retryWrites=true&w=majority  
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration