server:
  port: 8090
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl: 
      defaultZone: http://bank-discovery:8761/eureka
  instance:
    prefer-ip-address: true
    #hostname: bank-discovery
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: microservice-bank-gateway
  cloud:
    gateway:
      routes:
        - id: microservice-passive-accounts
          uri: http://localhost:8082
          predicates: 
          - Path=/passive-accounts/**
      discovery:
        locator:
          enabled: true
    loadbalancer:
      ribbon:
        enabled: false
          
 